# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.twig_extension:
      class: AppBundle\Twig\AppExtension
      public: false
      tags:
          - { name: twig.extension }
  app.webservice_user_provider:
          class: AppBundle\Security\CabinetUserProvider
  app.token_authenticator:
          class: AppBundle\Security\TokenAuth
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
